name: Deploy
on:
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: NaySoeWinYoma/lambda-actions
        with:
          aws-key: "UIUSHFOSOSOSOW"